# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16cd8389b7a0f66a2d5fc98aa99a07fef33d5137ae5fc3c7ff6619031982e103e00fc8037eb3d3f7454aba447a1a8ce751046b68292be50ddc1b30a9e301f5e9

test:
  secret_key_base: 1889053c89b181442ccf66a766773e58e7a7bc33296e947206f0a1cfd69f548d0d94796590fb10adb361f6e2997354cd15daf6da6bbefa3771ef2bbb2b56780e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1889053c89b181442ccf66a766773e58e7a7bc33296e947206f0a1cfd69f548d0d94796590fb10adb361f6e2997354cd15daf6da6bbefa3771ef2bbb2b56780e
